name: coachhub
description: A fitness coaching platform connecting trainees with certified coaches.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  nested: ^1.0.0
  go_router: ^10.2.0
  dio: ^5.3.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^8.0.0
  socket_io_client: ^2.0.2
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  http_parser: ^4.0.2
  timeago: ^3.6.0
  lottie: ^2.7.0
  web_socket_channel: ^2.4.0
  intl: any
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  # flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  intl_translation: ^0.20.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/icons/
    - assets/icons/features/
    - assets/fonts/
    - assets/icons/navigation/
    - assets/icons/reset/
    - assets/animations/

  fonts:
    - family: ErasITCDemi
      fonts:
        - asset: assets/fonts/eras-itc-demi.ttf
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria.ttf